### ISSUE TITLE
differences 

### ISSUE THREAD

**Issue by oym050922021** [RRRaymond/Multiview-Stereo#1]
Thank you very much for the open-source ACMMP code. 
May I ask what the differences are between this code and the original ACMMP (GhiXu/ACMMP) code? Thank you!

**Comment by RRRaymond** [comment]
hello, oym. I plan to conduct secondary development on the original repo, but there have been some delays in my plans recently. At present, the repository has modified the  python scripts to make view selection faster. Other aspects are changes to the code structure, and there is no difference in functionality.
